stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.12-slim
  script:
    - pip install --no-cache-dir -r requirements.txt
    - echo "Build step complete"

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pytest || echo "Add tests to enable this step"

deploy:
  stage: deploy
  script:
    - echo "Deploy step (customize for your environment)"
  when: manual
