name: Backend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install --no-cache-dir -r requirements.txt
      - run: echo "Build step complete"
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:latest .
      # Uncomment and configure below to push to a registry
      # - name: Log in to registry
      #   run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login <registry-url> -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      # - name: Push Docker image
      #   run: docker push <registry-url>/${{ github.repository }}:latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install --no-cache-dir -r requirements.txt
      - run: pytest || echo "Add tests to enable this step"
